apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-${NAMESPACE}
  namespace: argocd
  # annotations:
  #   notifications.argoproj.io/subscribe.on-sync-succeeded.slack: my_channel
  annotations:
    notifications.argoproj.io/subscriptions: |
      - trigger: [on-scaling-replica-set, on-rollout-updated, on-rollout-step-completed]
        destinations:
          - service: slack
            recipients: [my-channel-1, my-channel-2]
      - trigger: [on-rollout-aborted, on-analysis-run-failed, on-analysis-run-error]
        destinations:
          - service: slack
            recipients: [my-channel-21, my-channel-22]
spec:
  project: default
  source:
    repoURL: ${GIT_REPO}
    targetRevision: deploy
    path: argocd/env/${NAMESPACE}
  destination: 
    server: ${SERVER}
    namespace: gitops-multienv
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
